version: '3.8'

services:
  # 開発環境
  app-dev:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    command: npm run dev -- --host 0.0.0.0
    profiles:
      - dev

  # 本番環境
  app-prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    profiles:
      - prod

  # テスト環境
  app-test:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    env_file:
      - .env.local
    command: npm run test
    profiles:
      - test